# Generated by Django 5.0.1 on 2024-04-11 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_remove_perfil_tipo_entrenamiento_perfil_genero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='planentrenamiento',
            name='ejercicios',
        ),
        migrations.RemoveField(
            model_name='ejerciciorecuperacion',
            name='grupos_musculares',
        ),
        migrations.RemoveField(
            model_name='planejerciciorecuperacion',
            name='ejercicio_recuperacion',
        ),
        migrations.RemoveField(
            model_name='planentrenamiento',
            name='ejercicios_recuperacion',
        ),
        migrations.RemoveField(
            model_name='planentrenamiento',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='planejercicio',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planejerciciorecuperacion',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='planentrenamiento',
            name='tipo_entrenamiento',
        ),
        migrations.RemoveField(
            model_name='planentrenamiento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='plannutricional',
            name='plan_entrenamiento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='dias_entrenando',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='experiencia_entrenamiento',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apellido',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='condicion_fisica',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=None),
        ),
        migrations.AddField(
            model_name='perfil',
            name='condiciones_medicas',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='perfil',
            name='deporte_practicado',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_Nacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_de_registro',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivos',
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name='DietaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida1', models.TextField(default=None)),
                ('comida2', models.TextField(default=None)),
                ('comida3', models.TextField(default=None)),
                ('comida4', models.TextField(default=None)),
                ('comida5', models.TextField(default=None)),
                ('comida6', models.TextField(default=None)),
                ('fecha', models.DateField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamiento_Del_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equp_gimnasio', models.TextField(default=None)),
                ('equp_casa', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=None)),
                ('rutina', models.TextField(default=None)),
                ('duracion', models.TimeField(default=None)),
                ('lesiones', models.TextField(default=None)),
                ('opinion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesion', models.TextField(default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='GrupoMuscular',
        ),
        migrations.DeleteModel(
            name='EjercicioRecuperacion',
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
        migrations.DeleteModel(
            name='PlanEjercicio',
        ),
        migrations.DeleteModel(
            name='PlanEjercicioRecuperacion',
        ),
        migrations.DeleteModel(
            name='TipoEntrenamiento',
        ),
        migrations.DeleteModel(
            name='PlanEntrenamiento',
        ),
        migrations.DeleteModel(
            name='PlanNutricional',
        ),
    ]
