# Generated by Django 5.0.1 on 2024-05-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_alter_dietadiaria_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='deporte_practicado',
            field=models.CharField(choices=[('SOCCER', 'Soccer'), ('BASKETBALL', 'Basketball'), ('VOLLEYBALL', 'Volleyball'), ('UNDERWATER HOCKEY', 'Underwater Hockey'), ('TENNIS', 'Tennis'), ('TABLE TENNIS', 'Table Tennis'), ('ATHLETICS', 'Athletics'), ('CYCLING', 'Cycling'), ('CALISTHENICS ', 'Calisthenics'), ('HOCKEY ', 'Hockey'), ('ARCHERY ', 'Archery'), ('OTHER', 'Other')], default='OTROS', max_length=21),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-binary'), ('TRANSGENDER', 'Transgender'), ('GENDERQUEER', 'Genderqueer'), ('GENDERFLUID', 'Genderfluid'), ('AGENDER', 'Agender'), ('BIGENDER', 'Bigender'), ('TWO_SPIRIT', 'Two-spirit'), ('OTHER', 'Other'), ('CISGENDER', 'Cisgender'), ('GENDER_QUESTIONING', 'Gender questioning'), ('GENDER_NONCONFORMING', 'Gender nonconforming'), ('PANGENDER', 'Pangender'), ('DEMIBOY', 'Demiboy'), ('DEMIGIRL', 'Demigirl'), ('ANDROGYNE', 'Androgyne'), ('NEUTROIS', 'Neutrois'), ('GENDERFLUX', 'Genderflux'), ('THIRD_GENDER', 'Third gender'), ('BI_GENDER', 'Bi-gender'), ('GENDER_EXPANSIVE', 'Gender expansive'), ('GENDER_VARIANT', 'Gender variant'), ('INTERSEX', 'Intersex'), ('THIRD_SEX', 'Third sex'), ('MAHORAGA', 'Mahoraga'), ('ITACHI', 'Itachi'), ('BOEING_AH_64_APACHE', 'Boeing AH-64 Apache'), ('GOKU', 'Goku'), ('DECEPTICON', 'Decepticon'), ('OPTIMUS_PRIME', 'Optimus prime'), ('PERRO', 'Perro'), ('GATO', 'Gato'), ('OBAMA', 'Obama'), ('NONE', 'None'), ('PREFER_NOT_TO_SAY', 'Prefer Not to Say')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivos',
            field=models.CharField(choices=[('MAXIMUM FAT LOSS', 'Maximum Fat Loss'), ('SOME FAT LOSS', 'Some Fat Loss'), ('MANTAIN', 'Maintain'), ('STEADY GAIN', 'Steady Gain'), ('GAIN', 'Gain')], default='MANTAIN', max_length=21),
        ),
    ]
