# Generated by Django 5.0.1 on 2024-05-19 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_alter_macros_calorias_alter_macros_carbohidratos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='macros',
        ),
    ]
