# Generated by Django 5.0.1 on 2024-05-19 07:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0009_macros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Macros',
            new_name='Macros_Insanas',
        ),
    ]
