# Generated by Django 5.0.1 on 2024-05-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_rename_macros_macros_insanas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Macros_Insanas',
        ),
    ]
