# Generated by Django 5.0.1 on 2024-05-19 07:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0012_datos_para_comer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datos_Para_Comer',
            new_name='Macros',
        ),
    ]
