# Generated by Django 5.0.1 on 2024-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0015_alter_dietadiaria_comida1_alter_dietadiaria_comida2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietadiaria',
            name='comida1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dietadiaria',
            name='comida2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dietadiaria',
            name='comida3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dietadiaria',
            name='comida4',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dietadiaria',
            name='comida5',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='dietadiaria',
            name='comida6',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
