# Generated by Django 5.0.1 on 2024-05-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0017_alter_dietadiaria_comida1_alter_dietadiaria_comida2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dieta_semanal',
            old_name='domingo',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='rutina_semanal',
            old_name='domingo',
            new_name='horario',
        ),
        migrations.RemoveField(
            model_name='dieta_semanal',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='dieta_semanal',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='dieta_semanal',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='dieta_semanal',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='dieta_semanal',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='dieta_semanal',
            name='viernes',
        ),
        migrations.RemoveField(
            model_name='rutina_semanal',
            name='jueves',
        ),
        migrations.RemoveField(
            model_name='rutina_semanal',
            name='lunes',
        ),
        migrations.RemoveField(
            model_name='rutina_semanal',
            name='martes',
        ),
        migrations.RemoveField(
            model_name='rutina_semanal',
            name='miercoles',
        ),
        migrations.RemoveField(
            model_name='rutina_semanal',
            name='sabado',
        ),
        migrations.RemoveField(
            model_name='rutina_semanal',
            name='viernes',
        ),
    ]
