# Generated by Django 5.0.1 on 2024-05-20 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_rename_domingo_dieta_semanal_horario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='duracion',
        ),
        migrations.AlterField(
            model_name='historial',
            name='rutina',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='historial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
