# Generated by Django 5.0.1 on 2024-05-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0020_alter_lesiones_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesiones',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
